spring.application.name=eventhub-api
spring.profiles.active=dev
app.version=1.0.0

# =====================
# MySQL Database
# =====================
spring.datasource.url=jdbc:mysql://localhost:3306/eventhubdb
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=Nikitha@@89
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# =====================
# data.sql runs after JPA creates tables
# =====================
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=never

# =====================
# Swagger / OpenAPI
# =====================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

# =====================
# Logging
# =====================
logging.level.com.eventhub=DEBUG
logging.level.org.springframework.cache=DEBUG
logging.file.name=logs/eventhub.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
springdoc.packagesToScan=com.eventhub.api
springdoc.pathsToMatch=/api/**
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss